### PR TITLE
Drop inline issues

### LINKED ISSUE #21: Remove inline issues
I suggest we remove the verbose inline issues that somewhat clutter the spec.

The issues are found in the [spec repo issues](https://github.com/w3c/geolocation-api/issues) as usual.

### PR DESCRIPTION
**Pull request by anssiko**
Fix #21

### CODE REVIEW

**Comment by anssiko** [comment]
PTAL @reillyeon.

This is an editorial change. I feel e.g. [ISSUE-13](https://w3c.github.io/geolocation-api/#h-issue-0) is confusing and not appropriate inline, so proposing we remove all inline issues for consistency, farm them to GH issues (ReSpec pulls them dynamically from there anyways).

(FYI @xfq - it seems I can't assign reviewers via GH UI for this spec, can you fine-tune the GH configuration?)

**Comment by reillyeon** [comment]
@plehegar, I'm looking at 9fbfe7565fbbfe6215fbad633abacc8cb1003c58 and I don't see a motivation for adding issue references directly into the specification. Is there a W3C policy on this?

**Comment by plehegar** [comment]
@reillyeon , there is no policy on it. It was a simple matter of making sure folks were aware of issues in the past. Fine to be removed imho.

**Comment by plehegar** [comment]
@anssiko , I see you have admin rights on the repo, so you should be fine to do what you need.

**Comment by anssiko** [comment]
Thanks for the review. No concerns to drop the inline issues so merging this now.

**Pull request merged**
