### PR TITLE
Callback with error if doc is not fully active

### LINKED ISSUE #96: Error when method are called on not fully active docs
Speaking to @saschanaz, they suggested that `watchPosition()` and `getCurrentPosition()` should invoke the error callbacks if the document is not fully active. 

This makes sense in particular for promise-wrapped code, which would otherwise get stuck.

```JS
// current spec, this doesn't proceed in the odd case where the geo 
// object is from a non-fully active doc. 
await new Promise((res, rej) => geo.getCurrentPosition(res, rej));
```

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #96 

The following tasks have been completed:

 * [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/29799)

Implementation commitment:

 * [ ] WebKit (https://bugs.webkit.org/show_bug.cgi?id=228319)
 * [ ] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1233329)
 * [x] Gecko https://phabricator.services.mozilla.com/D117273

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/97.html" title="Last updated on Jul 27, 2021, 8:29 AM UTC (b92947d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/97/f4605e5...b92947d.html" title="Last updated on Jul 27, 2021, 8:29 AM UTC (b92947d)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Gecko patch: https://phabricator.services.mozilla.com/D117273

**Comment by reillyeon** [comment]
I've filed an issue against Chromium for this and updated the summary. Any chance the test you've added in the Gecko patch could be added to WPT instead?

**Review by reillyeon — APPROVED** [review]
This is one of the first instances I've seen where the behavior of calling a method on a non-fully active document is well-defined. It is something I always need to handle in Chromium (because non-fully active documents in Blink have a rather conspicuous null pointer) but haven't ever specified.

**Comment by marcoscaceres** [comment]
Thanks @reillyeon! And I again have to give a huge shout out to @rakina and co. for producing that TAG guide and for her guidance - and to @saschnas for a super detailed review over on the Gecko side, who caught the potential issue when used with promises. 

I'll see if I can create a WPT test. The challenge I've been facing is that the page requires permission to use the API. But I'll see if Webdriver, via WPT, lets me grant a page permission to use the API... Oh! might be in luck!

```JS
 await test_driver.set_permission({name: 'geolocation'}, 'granted');
``` 

Re non fully active in general: yeah, I've been finding really weird behavior... not sure if you are following the Permission's one, where (unsurprisingly) Chrome and Firefox are producing different results:

https://github.com/w3c/permissions/issues/162#issuecomment-886409154
 
These are a lot of fun to work on tho! So please ping if there are other APIs that could use a look over.

**Comment by marcoscaceres** [comment]
Ok, WPT is up https://github.com/web-platform-tests/wpt/pull/29799 - however, I'm unsure who to tag for review? @reillyeon can you suggest anyone (or review it?).  

That reminds me... we need to find new folks to review the tests. The current set listed over at WPT don't appear to be very active in this space as they might have moved onto other things.

**Comment by marcoscaceres** [comment]
Filed WebKit bug https://bugs.webkit.org/show_bug.cgi?id=228319

**Comment by saschanaz** [comment]
> Ok, WPT is up https://github.com/web-platform-tests/wpt/pull/29799 - however, I'm unsure who to tag for review? @reillyeon can you suggest anyone (or review it?).  
> 
> That reminds me... we need to find new folks to review the tests. The current set listed over at WPT don't appear to be very active in this space as they might have moved onto other things. 
>  

It can be included the gecko patch so that it can be automatically upstreamed.

**Comment by marcoscaceres** [comment]
@saschanaz wrote: 
> It can be included the gecko patch so that it can be automatically upstreamed.

I was hoping to do that, but Gecko doesn't implement `test_driver.set_permission()` yet 😢. I could still bundle it in, if you think it's still worth while.

**Comment by saschanaz** [comment]
Oops!

@jgraham Are we planning to implement `test_driver.set_permission()` in the foreseeable future?

**Comment by marcoscaceres** [comment]
Good news! WebKit patch inbound for this too! https://bugs.webkit.org/show_bug.cgi?id=228319 🎉

**Comment by marcoscaceres** [comment]
@reillyeon, could you by chance point me to how fully active checks are done in Chromium? With a little guidance, maybe I can slap together a Chromium patch? ☺️

**Comment by reillyeon** [comment]
I left notes on how to do this on https://bugs.chromium.org/p/chromium/issues/detail?id=1233329.

**Pull request merged**
