### PR TITLE
Default errorCallback to null

### LINKED ISSUE #61: errorCallback parameter to getPosition() and watchPosition() is nullable in all major browser engines
errorCallback parameter to getPosition() and watchPosition() is nullable in all major browser engines (tested WebKit, Gecko and Blink). However, it is not marked as nullable in the specification. Changing this behavior in browser engines would be a compatibility risk so I suggest we update the specification instead.

Note that there is already a web-platform-test relying on errorCallback being nullable:
https://w3c-test.org/geolocation-API/PositionOptions.https.html

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #61

The following tasks have been completed:

 * [x] Modified Web platform tests - https://w3c-test.org/geolocation-API/PositionOptions.https.html

Implementation commitment:

 * [ ] WebKit 
 * [x] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1153081)
 * [X] Gecko

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/62.html" title="Last updated on Mar 18, 2021, 9:38 PM UTC (4e91236)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/62/9f5d7e9...4e91236.html" title="Last updated on Mar 18, 2021, 9:38 PM UTC (4e91236)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@cdumez, I've changed the IDL to match what Gecko has (which, IIUC, should match the desired behavior). However, you might need to update WebKit to default `errorCallback = null`. 

https://github.com/WebKit/WebKit/blob/main/Source/WebCore/Modules/geolocation/Geolocation.idl

**Review by reillyeon — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Thanks for the review, @reillyeon!

**Comment by marcoscaceres** [comment]
Just noting that WebKit's IDL parser doesn't support `= null` or `= {}` yet.

**Comment by cdumez** [comment]
> Just noting that WebKit's IDL parser doesn't support `= null` or `= {}` yet.

Does it really matter? Our behavior is correct here. Our idl generator assumes null is the default value for optional nullable parameters.

**Comment by marcoscaceres** [comment]
> Does it really matter? Our behavior is correct here. Our idl generator assumes null is the default value for optional nullable parameters.

No, it doesn't matter :) Just wanted a record of it in case anyone goes looking as to why the IDL in WebKit doesn't exactly match the spec is all (or tries to compile with the updated IDL, as I did).

**Pull request merged**
