### PR TITLE
Addition: expose .toJSON() on GeolocationCoordinates + GeolocationPosition

### LINKED ISSUE #145: Add support for converting Geolocation Position+Coordinates to JSON (object)
Given `GeolocationCoordinates` are just nullable doubles, it would be nice if GeolocationCoordinates exposed a (WebIDL) default `.toJSON()` method.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #145 

The following tasks have been completed:

 * [x] Modified Web platform tests  - We can't test this explicitly until #146, but we get the IDL tests for free at least. 

Implementation commitment:

 * [X] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=272434) 
   * https://github.com/WebKit/WebKit/pull/27063
   *  https://github.com/WebKit/WebKit/pull/27127 
 * [X] [Chromium](https://issues.chromium.org/issues/333511557)
   * https://chromium-review.googlesource.com/c/chromium/src/+/5446324
 * [ ] [Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1890706)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/pull/147.html" title="Last updated on Apr 15, 2024, 9:00 PM UTC (c9c9574)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/geolocation-api/147/10b168f...c9c9574.html" title="Last updated on Apr 15, 2024, 9:00 PM UTC (c9c9574)">Diff</a>

### CODE REVIEW

**Comment by reillyeon** [comment]
I filed a Chromium issue to track this. Please file issues for WebKit and Gecko.

**Comment by marcoscaceres** [comment]
Filed Gecko and WebKit bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1890706

@saschanaz, would you be the right person to comment on this?

**Comment by marcoscaceres** [comment]
Sent a PR for WebKit https://github.com/w3c/geolocation-api/issues/146

**Comment by saschanaz** [comment]
👍 from Mozilla.

**Comment by marcoscaceres** [comment]
@reillyeon, if all looks good, could you give it a ✅ 🙏 

Patches ready to land on the WebKit side.

**Comment by reillyeon** [comment]
I'm writing up the "Intent to Prototype and Ship" email for the Blink launch process and I just want to make sure I understand the motivation for this change. Are tests planning to use `JSON.stringify()` or is it that much easier to compare objects when they are "plain old JavaScript objects" than when they are instances of a WebIDL interface?

I noted when I was writing tests for this change in Chromium that the output of `JSON.stringify()` is not well defined (due to property order) so it doesn't seem appropriate for tests.

**Comment by saschanaz** [comment]
Do we have context about why GeolocationPosition is not a dictionary? 🤔

**Review by reillyeon — APPROVED** [review]

**Comment by marcoscaceres** [comment]
> Do we have context about why GeolocationPosition is not a dictionary?

Just because of legacy, @saschanaz (given the API is like 10+ years old). If we were doing the API today, it would definitely just have been a dictionary.

**Pull request merged**
